bayesimpact/ma-voie

- src/components/header_section.tsx
- src/translations/en/translation_i18next.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie-internal/630)
> [Homepage] redundancy with the text in the CTA

- LICENSE
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/634)
> Add LICENSE file for the opensource repo

- src/components/partner_card.tsx
Fix #636
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/639)
> Make the partner card button more obviously clickable.

- server/firestore.rules
- src/store/partners.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/641)
> [Partners] Updated openclassrooms trainings (mixed up)

- src/store/partners.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/642)
> [Partners] Update link to chance (requested by Chance)

- package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/650)
> [Bug Fix] Fix the resolved types for anymatch.

- src/components/pages/mission.tsx
Fix #644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/653)
> [Mission Page] Add a video in the mission page

- server/firestore.rules
- src/store/partners.json
Fix #651
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/652)
> [Partners] Deactivate Inco - in code training

- server/firestore.rules
- src/store/partners.json
Fix #646
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/654)
> [Partners] Add a new training for Generation partner

- src/components/create_account_popup.tsx
To test it: click on Commencer
PATH=/etapes
Fix #655
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/656)
> [Fix] Make the signup button clickable on mobile.

- demo/README.md
- demo/ma-voie-demo.docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/658)
> [Master Main] Add FDR configuration.

- src/components/pages/forgot_password.tsx
- src/components/pages/login.tsx
- src/components/pages/password.tsx
PATH=/connexion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/661)
> [Fix] Correct bug on Safari on input texts line height.

- src/components/pages/account.tsx
PATH=/compte
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/660)
> [Fix] Force email to be lowercased.

- package.json
- src/components/header.tsx
- src/components/pages/main.tsx
PATH=/definition/partenaires
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/662)
> [Fix] Prevent from unlogged users to access to logged pages only.

- server/Dockerfile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/664)
> [Fix] Delete openjdk install.

- server/Dockerfile
- server/firebase.json
- server/package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/665)
> [Deploy] Update the node server environment to 14.

- demo/ma-voie-demo.docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/667)
> [Demo] Add parameters for demo.

- src/components/pages/login.tsx
- src/translations/en/translation_i18next.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/668)
> [Login] Add an error message translation.

- src/store/partners.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/671)
> [Partners] Update oreegami and generation (customer care) links.

- test/webpack/colors_test.ts
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/676)
> small code to test release branch

- .circleci/config.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/682)
> [Clean Code] Remove useless gcloud instruction in CI.

- src/components/pages/main.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/684)
> Analytics feature with consent

- src/components/pages/main.tsx
- src/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bayesimpact/ma-voie/694)
> Fix cookies call
